### ISSUE TITLE
add parenthesis-less function calling

### ISSUE THREAD

**Issue by dots-git** [dots-git/vinegar#1]
with this syntax:

```
function:
    arg2: "hello world"
    arg1
    arg3: "example"
```

as described in the docs
